<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Mesaj_Companie_Client = new HashSet<Mesaj_Companie_Client>();
            this.Ratings = new HashSet<Rating>();
            this.Ratings1 = new HashSet<Rating>();
            this.Relaties = new HashSet<Relatie>();
            this.Relaties1 = new HashSet<Relatie>();
            this.Aptitudinis = new HashSet<Aptitudini>();
        }
    
        public int ID_Client { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<System.DateTime> Data_Nasterii { get; set; }
        public string Email { get; set; }
        public byte[] Poza { get; set; }
        public string Facultate_absolvita { get; set; }
        public int ID_sex { get; set; }
        public int ID_statut_social { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Nationalitate { get; set; }
        public string Limbi_straine { get; set; }
        public string Username { get; set; }
        public string Parola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesaj_Companie_Client> Mesaj_Companie_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relatie> Relaties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relatie> Relaties1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aptitudini> Aptitudinis { get; set; }
=======
﻿using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace proiect
{

    public partial class Client : Form
    {
        public static string search;
        public static int c_panel_Details = 0;
        public static int c_panel_Notification = 0;
        public static int open_message = 0;
        public static string rating;
        public static DataGrid grid;

        public Client()
        {
            InitializeComponent();
            picMessaging.Image = Image.FromFile("message.png");
            picRequest.Image = Image.FromFile("notification.png");
            picMe.Image = Image.FromFile("profile.png");

            panelDetails.Visible = false;
            panelNotification.Visible = false;

            lbUsername.Text = "Raducanu Cristian(Kinstown)"; //aici trebuie sa puneti voi nume+prenume
            txtAddress.Text = "acasa";
            txtBirth.Text = "21.12.2017";
            txtEmail.Text = "@gmail.com";
            txtNationality.Text = "roman";
            txtPhone.Text = "0741413131";
            txtSex.Text = "gay";
            txtStatus.Text = "singur";
            txtUniversiy.Text = "ATM";

            //aici zic eu sa puneti skills
            ListViewItem item1 = new ListViewItem("item1");
            ListViewItem item2 = new ListViewItem("item2");
            ListViewItem item3 = new ListViewItem("item3");
            listSkils.Items.Add(item1);
            listSkils.Items.Add(item2);
            listSkils.Items.Add(item3);

        }

        
        private void lbDetails_Click(object sender, EventArgs e)
        {
            c_panel_Details++;
            if (c_panel_Details % 2 == 0)
                panelDetails.Visible = true;
            else
                panelDetails.Visible = false;
        }

        private void picRequest_Click(object sender, EventArgs e)
        {
            c_panel_Notification++;
            if (c_panel_Notification % 2 == 0)
                panelNotification.Visible = true;
            else
                panelNotification.Visible = false;

        }

        private void picMessaging_Click(object sender, EventArgs e)
        {
            panelDetails.Visible = false;
            panelNotification.Visible = false;

                Form form = new Messaging();
                form.Show();


        }

        private void trackBar_Scroll(object sender, EventArgs e)
        {
            rating = trackBar.ToString();
        }

        private void txtSearch_TextChanged(object sender, EventArgs e)
        {
            search = txtSearch.ToString();
        }

        private void bSearch_Click(object sender, EventArgs e)
        {
            //aici trebuie sa cautati in baza de date si sa afisati in gridView
            if (search != null)
            {
                Form form = new Search(search);
                form.Show();
            }
            else
            {
                MessageBox.Show("Search box is empty, can't search",
                    "WARNING",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning);
            }
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            MessageBox.Show("Friend requesst accepted",
                "Information",
                MessageBoxButtons.OK,
                MessageBoxIcon.Information);

        }

        private void btLogOut_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }
>>>>>>> d58e1b2406af03e621f5e893ebafa7d330a9bc2b
    }
}
