<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companie()
        {
            this.Mesaj_Companie_Client = new HashSet<Mesaj_Companie_Client>();
            this.Aptitudinis = new HashSet<Aptitudini>();
        }
    
        public int ID_Companie { get; set; }
        public string Director_companie { get; set; }
        public string Nume_companie { get; set; }
        public string Adresa_companie { get; set; }
        public string Email_companie { get; set; }
        public string Telefon_companie { get; set; }
        public string UsernameC { get; set; }
        public string ParolaC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesaj_Companie_Client> Mesaj_Companie_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aptitudini> Aptitudinis { get; set; }
=======
﻿using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace proiect
{
    public partial class Companie : Form
    {
        public static string search;
        public static DataGrid data;
        public static int c_panel_Details = 0;
        public static int open_message=0;

        public Companie()
        {
            InitializeComponent();
            picMessaging.Image = Image.FromFile("letter.png");

            panelDetails.Visible = false;

            lbCompanyName.Text = "companie"; //aici trebuie sa puneti voi nume+prenume
            txtCEO.Text = "eu";
            txtAddress.Text = "acasa";
            txtEmail.Text = "@gmail.com";
            txtPhone.Text = "0741413131";
            txtSkillsRequest.Text = "toate\n mere\n pere";
        }

        private void lbDetails_Click(object sender, EventArgs e)
        {
            c_panel_Details++;
            if (c_panel_Details % 2 == 0)
                panelDetails.Visible = true;
            else
                panelDetails.Visible = false;
        }

        private void picMessaging_Click(object sender, EventArgs e)
        {
            panelDetails.Visible = false;

                Form form = new Messaging();
                form.Show();
        }

        private void txtSearch_TextChanged(object sender, EventArgs e)
        {
            search = txtSearch.ToString();
        }

        private void txtSearch_TextChanged_1(object sender, EventArgs e)
        {
            search = txtSearch.ToString();
        }

        private void btSearch_Click(object sender, EventArgs e)
        {
            if (search != null)
            {
                Form form = new SearchC(search);
                form.Show();
            }
            else
            {
                MessageBox.Show("Search box is empty, can't search",
                    "WARNING",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Warning);
            }
        }

        private void btLogOut_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }
>>>>>>> d58e1b2406af03e621f5e893ebafa7d330a9bc2b
    }
}
